credentials:
  oauth_consumer_key: XjY7q0CYwRxSBzCpUeRDzQ
  oauth_token: 214373359-jn77FNlrKEajR4Gpp9l5msb1KXCGXZ7QeJPtt5TF
  oauth_consumer_secret: cuseCPmxY4taUEmouOhXIvR7MVSUWdRKjKHvHKgVvOk
  oauth_token_secret: tO5hW1ye3myBnT78DspVbTKWFgadvKeU1EOiV3o5Tg
params:
  track: twitter
